name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Report timezone information
      run: python -c "import time; print((time.timezone, time.altzone, time.daylight, time.tzname, time.time()))"
    - name: Install tox
      run: python -m pip install --upgrade tox tox-gh-actions coveralls
    - name: Run tox
      run: tox
    - name: Publish coverage
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
